services:
  umami:
       container_name: analytics
       image: ghcr.io/umami-software/umami:postgresql-latest
       ports:
           - "3000:3000"

       environment:
           DATABASE_URL: postgresql://umami:umami123@umami-db:5432/umami
           DATABASE_TYPE: postgresql
           HASH_SALT: ASWALKLSA446
       depends_on:
           - umami-db
       networks:
         - net_portfolio

  umami-db:
       container_name: analytics-db
       image: postgres:12-alpine
       environment:
           POSTGRES_DB: umami
           POSTGRES_USER: umami
           POSTGRES_PASSWORD: umami123
       volumes:
           - ./analytics/data:/var/lib/postgresql/data
       networks:
         - net_portfolio

  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: portfolio-database
    ports:
      - 3306:3306
    volumes:
      - ./database/volumes:/var/lib/mysql
      - ./database/.backups:/backup
    hostname: forms
    networks:
      - net_portfolio
    healthcheck:
        test: ["CMD","mysql", "-u", "root", "-proot"]
        interval: 30s
        timeout: 10s
        retries: 5

  dbBackup:
    image: fradelg/mysql-cron-backup
    container_name: portfolio-backup
    depends_on:
      - database
    volumes:
      - ./database/.backups:/backup
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=forms
      - CRON_TIME=0 0 * * *
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - TIMEOUT=30s
      - INIT_BACKUP=1  
    networks:
      - net_portfolio

  fastapi:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "9000:9000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - net_portfolio

  management:
    image: adminer
    container_name: database-management
    ports:
      - 8080:8080
    networks:
      - net_portfolio

  web:
    build: ./web-host/react-portfolio/
    container_name: web-host
    ports:
      - "443:5173" 
    volumes:
      - ./web-host/react-portfolio:/app
    networks:
      - net_portfolio

networks:
  net_portfolio:
      driver: bridge
      name: net_portfolio
