services:
  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: portfolio-database
    ports:
      - 3306:3306
    volumes:
      - ./database/volumes:/var/lib/mysql
    hostname: forms
    networks:
      - net_portfolio
    healthcheck:
        test: ["CMD","mysql", "-u", "root", "-proot"]
        interval: 30s
        timeout: 10s
        retries: 5
  fastapi:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "9000:9000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - net_portfolio
  management:
    image: adminer
    container_name: database-management
    ports:
      - 8080:8080
    networks:
      - net_portfolio
  web:
    build: ./web-host/react-portfolio/
    container_name: web-host
    ports:
      - "443:5173" 
    volumes:
      - ./web-host/react-portfolio:/app
    networks:
      - net_portfolio
networks:
  net_portfolio:
      driver: bridge
      name: net_portfolio
